#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2018 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.6
COMPONENT_MNR_VERSION=	10
COMPONENT_ARCHIVE_HASH=	sha256:8615acc56646401f0ede97a767dfd27ce07a8ae9c952afdb57163b7234fe8426

PG_CONTRIB_LIBS+=	uuid-ossp

include ../meta-packages/postgresql/Makefile.common
