#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.6
COMPONENT_MNR_VERSION=	3
COMPONENT_ARCHIVE_HASH=	sha256:1645b3736901f6d854e695a937389e68ff2066ce0cde9d73919d6ab7c995b9c6

PG_CONTRIB_LIBS+=	uuid-ossp

include ../meta-packages/postgresql/Makefile.common
