#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.2
COMPONENT_MNR_VERSION=	23
COMPONENT_ARCHIVE_HASH=	sha256:0e6ecdfeed69030dac8d219ecd4c350ce45e9f2caa9d73e166e407e87afec450

PG_CONTRIB_BINS+=	pgbench

include ../meta-packages/postgresql/Makefile.common
