--- mg-20150323/GNUmakefile.~1~	2014-07-26 15:20:49.000000000 +0000
+++ mg-20150323/GNUmakefile	2015-04-11 15:20:50.809129426 +0000
@@ -7,17 +7,25 @@
 
 name=		mg
 
-prefix=		/usr/local
+prefix=		$(ECPREFIX)
 bindir=		$(prefix)/bin
 libdir=		$(prefix)/lib
 includedir=	$(prefix)/include
 mandir=		$(prefix)/man
 
-PKG_CONFIG=	/usr/bin/pkg-config
-INSTALL=	/usr/bin/install
-STRIP=		/usr/bin/strip
+PKG_CONFIG=	$(ECPREFIX)/bin/pkg-config
+INSTALL=	$(ECPREFIX)/bin/install
+STRIP=		$(ECPREFIX)/bin/strip
 
+DEAD=		-D__dead=__dead2
 UNAME:=		$(shell uname)
+ifeq ($(UNAME),SunOS)
+  OBJS+=	adirent.o fgetln.o fparseln.o reallocarray.o strtonum.o
+  SUNOS_LIBS=	-lsocket -lnsl -lumem
+  CURSES_LIBS=	-lncurses -ltinfo
+  DEAD=		-D__dead=
+  CPPFLAGS=	-DDEFFILEMODE=0666
+endif
 ifeq ($(UNAME),FreeBSD)
   BSD_CPPFLAGS:=
   BSD_LIBS:=	-lutil
@@ -26,22 +34,22 @@
   BSD_LIBS:=	$(shell $(PKG_CONFIG) --libs libbsd-overlay)
 endif
 
-CURSES_LIBS=	-lcurses
+CURSES_LIBS?=	-lcurses
 
 CC?=		gcc
 CFLAGS?=	-O2 -pipe
 CFLAGS+=	-g -Wall
-CPPFLAGS=	-DFKEYS -DREGEX -DXKEYS
-CPPFLAGS+=	$(BSD_CPPFLAGS) -D__dead=__dead2
-LIBS=		$(CURSES_LIBS) $(BSD_LIBS)
+CPPFLAGS+=	-DFKEYS -DREGEX -DXKEYS
+CPPFLAGS+=	$(BSD_CPPFLAGS) $(DEAD) -I/ec/include
+LIBS=		$(CURSES_LIBS) $(BSD_LIBS) $(SUNOS_LIBS)
 
 
-OBJS=	autoexec.o basic.o bell.o buffer.o cinfo.o dir.o display.o \
+OBJS+=	autoexec.o basic.o bell.o buffer.o cinfo.o dir.o display.o \
 	echo.o extend.o file.o fileio.o funmap.o help.o kbd.o keymap.o \
 	line.o macro.o main.o match.o modes.o paragraph.o random.o \
 	re_search.o region.o search.o spawn.o tty.o ttyio.o ttykbd.o \
 	undo.o version.o window.o word.o yank.o
-OBJS+=	cmode.o cscope.o dired.o grep.o tags.o theo.o
+OBJS+=	cmode.o cscope.o dired.o grep.o tags.o
 
 
 # # Portability stuff.
