--- mg-20110120/Makefile.in.~1~	2011-01-03 12:16:05.000000000 +0000
+++ mg-20110120/Makefile.in	2011-08-05 14:11:17.194490514 +0100
@@ -15,7 +15,7 @@
 
 
 CC=		gcc
-CFLAGS?=	-O2 -pipe
+CFLAGS?=	-O2 -pipe -DBSD_COMP
 CFLAGS+=	-g -Wall -Werror
 LIBS= 		-lncurses
 
@@ -24,6 +24,7 @@
 
 
 OBJS= 	autoexec.o \
+	asprintf.o \
 	basic.o \
 	buffer.o \
 	cinfo.o \
