#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.5
COMPONENT_MNR_VERSION=	18
COMPONENT_ARCHIVE_HASH=	sha256:dfc940487ed5acd5f657d6d02d53a18f9699888d4b0f820071e4564ed2f9f3dd

PG_CONTRIB_LIBS+=	uuid-ossp

include ../meta-packages/postgresql/Makefile.common
