#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2018 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.5
COMPONENT_MNR_VERSION=	15
COMPONENT_ARCHIVE_HASH=	sha256:dbda3fdefd7f9fd5359a7989085aaef25c9f9d08816eda6378c2575d1ff55444

PG_CONTRIB_LIBS+=	uuid-ossp

include ../meta-packages/postgresql/Makefile.common
