--- logrotate-3.9.1/Makefile.~1~	2015-04-03 07:39:35.000000000 +0000
+++ logrotate-3.9.1/Makefile	2016-10-10 15:24:03.224307091 +0000
@@ -54,7 +54,7 @@
     CFLAGS = -D_GNU_SOURCE -D$(OS_NAME) -DVERSION=\"$(VERSION)\" $(RPM_OPT_FLAGS) $(LFS)
     CC ?= gcc
     CPP = $(CC) -E -M
-    INSTALL = /usr/ucb/install
+    INSTALL = install
     ifeq ($(CC),cc)
         CPP = cc -xM
     endif
@@ -90,7 +90,7 @@
     CFLAGS += -DSTATEFILE=\"$(STATEFILE)\"
 endif
 
-BINDIR = $(BASEDIR)/sbin
+BINDIR = $(BASEDIR)/bin
 MANDIR ?= $(BASEDIR)/man
 
 #--------------------------------------------------------------------------
