--- nail/Makefile.~1~	2007-04-14 15:26:00.000000000 +0000
+++ nail/Makefile	2012-11-26 17:13:18.051975506 +0000
@@ -6,18 +6,20 @@
 # See the file INSTALL if you need help.
 #
 
-PREFIX		= /usr/local
+CC		= gcc
+PREFIX		= /ec
 BINDIR		= $(PREFIX)/bin
 MANDIR		= $(PREFIX)/share/man
-SYSCONFDIR	= /etc
+SYSCONFDIR	= $(PREFIX)/etc
 
-MAILRC		= $(SYSCONFDIR)/nail.rc
-MAILSPOOL	= /var/mail
-SENDMAIL	= /usr/lib/sendmail
+MAILRC		= $(SYSCONFDIR)/mailx.rc
+MAILSPOOL	= $(PREFIX)/var/mail
+#SENDMAIL	= /usr/lib/sendmail
+SENDMAIL	= /ec/bin/exim
 
-DESTDIR		=
+#DESTDIR		= 
 
-UCBINSTALL	= /usr/ucb/install
+UCBINSTALL	= /ec/bin/install
 
 # Define compiler, preprocessor, and linker flags here.
 # Note that some Linux/glibc versions need -D_GNU_SOURCE in CPPFLAGS, or
@@ -46,7 +48,10 @@
 #INCLUDES	= -I$(MOZINC)/nspr -I$(MOZINC)/nss
 #LDFLAGS	= -L$(MOZLIB) -R$(MOZLIB)
 
-SHELL		= /bin/sh
+INCLUDES	= -I$(PREFIX)/include
+LDFLAGS	= -L$(PREFIX)/lib -R$(PREFIX)/lib -liconv
+
+SHELL		= /ec/bin/bash
 
 # If you know that the IPv6 functions work on your machine, you can enable
 # them here.
