#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 EveryCity Ltd. All rights reserved.
#

COMPONENT_FMRI=		runtime/ruby-24
COMPONENT_MJR_VERSION=	2.4
COMPONENT_MNR_VERSION=	6
COMPONENT_ARCHIVE_HASH=	sha256:de0dc8097023716099f7c8a6ffc751511b90de7f5694f401b59f2d071db910be

include ../../meta-packages/ruby/Makefile.common
