$NetBSD: patch-Makefile,v 1.6 2016/12/07 21:34:58 fhajny Exp $

Unlock install target.

--- a/Makefile.orig	2016-11-22 20:34:17.000000000 +0000
+++ b/Makefile
@@ -84,10 +84,6 @@ clean:
 	@echo Cleaning completed
 
 
-#------------------------------------------------------------------------
-#make install is validated only for Linux, OSX, kFreeBSD, Hurd and
-#FreeBSD targets
-ifneq (,$(filter $(shell uname),Linux Darwin GNU/kFreeBSD GNU FreeBSD))
 HOST_OS = POSIX
 
 install:
@@ -141,7 +137,6 @@ examples:
 	$(MAKE) -C $(PRGDIR) lz4
 	$(MAKE) -C examples test
 
-endif
 
 
 ifneq (,$(filter MSYS%,$(shell uname)))
