#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.3
COMPONENT_MNR_VERSION=	18
COMPONENT_ARCHIVE_HASH=	sha256:ad60d12a5a3dd0f6f5904c41b87e43eff49d3f74e45129fe52c5744366ff2fe0

PG_CONTRIB_BINS+=	pgbench

include ../meta-packages/postgresql/Makefile.common
