#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 EveryCity Ltd. All rights reserved.
#

POSTGRES_MJR_VERSION=		9.4
POSTGRES_MJR_VERSION_SHORT=	94

include ../../meta-packages/postgresql/PsycoPG2.common
