#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2011 EveryCity Ltd. All rights reserved.
#

include ../../make-rules/shared-macros.mk

COMPONENT_NAME=		shell-settings
COMPONENT_VERSION=	1.0

include ../../make-rules/ips.mk

PKGMANGLE = true
PKGLINT = true

download:

prep:

configure:

build:

install:
	rm -rf $(PROTO_DIR)
	mkdir -p $(PROTO_DIR)

test:		$(NO_TESTS)

clean:
	[ -d $(BUILD_DIR) ] && rm -rf $(BUILD_DIR)

clobber: clean

