--- pigz-2.3.1/Makefile.orig	2014-04-02 14:08:26.418829331 +0100
+++ pigz-2.3.1/Makefile	2014-04-02 14:08:35.022245789 +0100
@@ -1,5 +1,5 @@
-CC=cc
-CFLAGS=-O3 -Wall -Wextra
+CC?=cc
+CFLAGS?=-O3 -Wall -Wextra
 
 
 pigz: pigz.o yarn.o zopfli/deflate.o zopfli/blocksplitter.o zopfli/tree.o zopfli/lz77.o zopfli/cache.o zopfli/hash.o zopfli/util.o zopfli/squeeze.o zopfli/katajainen.o
