--- pigz-2.2.5/Makefile.~1~	2012-02-12 05:18:18.000000000 +0000
+++ pigz-2.2.5/Makefile	2012-11-16 16:50:56.340423277 +0000
@@ -1,8 +1,8 @@
-CC=cc
+CC=gcc
 CFLAGS=-O3 -Wall -Wextra
 
 pigz: pigz.o yarn.o
-	$(CC) -o pigz pigz.o yarn.o -lpthread -lz
+	$(CC) -o pigz pigz.o yarn.o -lpthread -lz $(LDFLAGS)
 	ln -f pigz unpigz
 
 pigz.o: pigz.c yarn.h
