--- whois-5.0.11/Makefile.orig	2011-04-13 21:24:37.687131615 +0100
+++ whois-5.0.11/Makefile	2011-04-13 21:25:21.826820245 +0100
@@ -1,4 +1,6 @@
 prefix = /usr
+CC=gcc
+LDFLAGS=-lnsl -lsocket
 
 CFLAGS = -g -O2
 
@@ -50,7 +52,7 @@
 endif
 
 ##############################################################################
-all: Makefile.depend whois mkpasswd #pos
+all: Makefile.depend whois
 
 ##############################################################################
 %.o: %.c
