#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright (c) 2010, 2011, Oracle and/or its affiliates. All rights reserved.
# Copyright 2011-2013 EveryCity Ltd. All rights reserved.
#

PATH.32=$(USRDIR)/bin:/usr/sfw/bin:/usr/ccs/bin
PATH.64=$(USRDIR)/bin/$(MACH64):$(USRDIR)/bin:/usr/bin:/usr/sfw/bin:/usr/ccs/bin
PATH=$(PATH.$(BITS))

ROOT=		/

WS_ARCHIVES=	$(WS_TOP)/archives
WS_LOGS=	$(WS_TOP)/$(MACH)/logs
WS_REPO=	$(WS_TOP)/$(MACH)/repo
WS_TOOLS=	$(WS_TOP)/tools
WS_COMPONENTS=	$(WS_TOP)/components
WS_TRANSFORMS=	$(WS_TOP)/transforms
WS_INCORPORATIONS=	$(WS_TOP)/incorporations
WS_LINT_CACHE=	$(WS_TOP)/$(MACH)/pkglint-cache

COMPONENT_DIR=	$(shell pwd)
SOURCE_DIR=	$(COMPONENT_DIR)/source/$(COMPONENT_SRC)
BUILD_DIR=	$(COMPONENT_DIR)/build
PROTO_DIR=	$(BUILD_DIR)/prototype/$(MACH)

# Deprecated - to be retired in preference of $(USRDIR) and $(APPLICATION_PREFIX)
ECPREFIX=/usr

# Default system paths for software delivery - do not override at a component
# level.
ETCDIR=		/etc
VARDIR=		/var
USRDIR=		/usr
MANIFESTDIR=	/var/svc/manifest
METHODDIR=	/var/svc/method
APPDIR=		$(USRDIR)
BINDIR.32 =	$(USRDIR)/bin
BINDIR.64 =	$(USRDIR)/bin/$(MACH64)
BINDIR=		$(BINDIR.$(BITS))
SBINDIR.32 =	$(BINDIR.32)
SBINDIR.64 =	$(BINDIR.64)
SBINDIR=	$(SBINDIR.$(BITS))
LIBDIR.32 =	$(USRDIR)/lib
LIBDIR.64 =	$(USRDIR)/lib/$(MACH64)
LIBDIR=		$(LIBDIR.$(BITS))
SHAREDIR=	$(USRDIR)/share
INCDIR=		$(USRDIR)/include
LOCALEDIR=	$(SHAREDIR)/locale
MANDIR=		$(SHAREDIR)/man
DOCDIR=		$(SHAREDIR)/doc
INFODIR=	$(SHAREDIR)/info
SHARELIBDIR=	$(SHAREDIR)/lib
MAN1DIR=	$(MANDIR)/man1
MAN1MDIR=	$(MANDIR)/man1m
MAN3DIR=	$(MANDIR)/man3
MAN4DIR=	$(MANDIR)/man4
MAN5DIR=	$(MANDIR)/man5

# System Paths
SYSTEMBINDIR=		/bin
SYSTEMSBINDIR=		/sbin
SYSTEMUSRBINDIR=	/system/usr/bin
SYSTEMUSRSBINDIR=	/system/usr/sbin

# Application Paths - used for application delivery. These can be overriden
# in a component Makefile to affect where the application is delivered to.
#
# To relocate an application use e.g. APPLICATION_PREFIX=$(APPDIR)/apache/2.2
# Note: Be sure to put such a macro before configure.mk or justmake.mk
APPLICATION_PREFIX=	$(USRDIR)
APPLICATION_ETCDIR=	$(ETCDIR)
APPLICATION_VARDIR=	$(VARDIR)
APPLICATION_BINDIR.32=	$(APPLICATION_PREFIX)/bin
APPLICATION_BINDIR.64=	$(APPLICATION_PREFIX)/bin/$(MACH64)
APPLICATION_BINDIR=	$(APPLICATION_BINDIR.$(BITS))
APPLICATION_SBINDIR.32=	$(APPLICATION_PREFIX)/bin
APPLICATION_SBINDIR.64=	$(APPLICATION_PREFIX)/bin/$(MACH64)
APPLICATION_SBINDIR=	$(APPLICATION_SBINDIR.$(BITS))
APPLICATION_LIBDIR.32=	$(APPLICATION_PREFIX)/lib
APPLICATION_LIBDIR.64=	$(APPLICATION_PREFIX)/lib/$(MACH64)
APPLICATION_LIBDIR=	$(APPLICATION_LIBDIR.$(BITS))
APPLICATION_SHAREDIR=	$(APPLICATION_PREFIX)/share
APPLICATION_INCDIR=	$(APPLICATION_PREFIX)/include
APPLICATION_LOCALEDIR=	$(APPLICATION_SHAREDIR)/locale
APPLICATION_MANDIR=	$(APPLICATION_SHAREDIR)/man
APPLICATION_DOCDIR=	$(APPLICATION_SHAREDIR)/doc
APPLICATION_INFODIR=	$(APPLICATION_SHAREDIR)/info
APPLICATION_SHARELIBDIR=	$(APPLICATION_SHAREDIR)/lib
APPLICATION_MAN1DIR=	$(APPLICATION_MANDIR)/man1
APPLICATION_MAN1MDIR=	$(APPLICATION_MANDIR)/man1m
APPLICATION_MAN3DIR=	$(APPLICATION_MANDIR)/man3
APPLICATION_MAN4DIR=	$(APPLICATION_MANDIR)/man4
APPLICATION_MAN5DIR=	$(APPLICATION_MANDIR)/man5

# PROTO_DIR shortcuts for convenience
PROTO_PREFIX=		$(PROTO_DIR)$(APPLICATION_PREFIX)
PROTO_ETCDIR=		$(PROTO_DIR)$(APPLICATION_ETCDIR)
PROTO_VARDIR=		$(PROTO_DIR)$(APPLICATION_VARDIR)
PROTO_BINDIR.32=	$(PROTO_DIR)$(APPLICATION_BINDIR.32)
PROTO_BINDIR.64=	$(PROTO_DIR)$(APPLICATION_BINDIR.64)
PROTO_BINDIR=		$(PROTO_DIR)$(APPLICATION_BINDIR)
PROTO_SBINDIR.32=	$(PROTO_DIR)$(APPLICATION_SBINDIR.32)
PROTO_SBINDIR.64=	$(PROTO_DIR)$(APPLICATION_SBINDIR.64)
PROTO_SBINDIR=		$(PROTO_DIR)$(APPLICATION_SBINDIR)
PROTO_LIBDIR.32=	$(PROTO_DIR)$(APPLICATION_LIBDIR.32)
PROTO_LIBDIR.64=	$(PROTO_DIR)$(APPLICATION_LIBDIR.64)
PROTO_LIBDIR=		$(PROTO_DIR)$(APPLICATION_LIBDIR)
PROTO_SHAREDIR=		$(PROTO_DIR)$(APPLICATION_SHAREDIR)
PROTO_INCDIR=		$(PROTO_DIR)$(APPLICATION_INCDIR)
PROTO_LOCALEDIR=	$(PROTO_DIR)$(APPLICATION_LOCALEDIR)
PROTO_MANDIR=		$(PROTO_DIR)$(APPLICATION_MANDIR)
PROTO_DOCDIR=		$(PROTO_DIR)$(APPLICATION_DOCDIR)
PROTO_INFODIR=		$(PROTO_DIR)$(APPLICATION_INFODIR)
PROTO_SHARELIBDIR=	$(PROTO_DIR)$(APPLICATION_SHARELIBDIR)
PROTO_MAN1DIR=		$(PROTO_DIR)$(APPLICATION_MAN1DIR)
PROTO_MAN1MDIR=		$(PROTO_DIR)$(APPLICATION_MAN1MDIR)
PROTO_MAN3DIR=		$(PROTO_DIR)$(APPLICATION_MAN3DIR)
PROTO_MAN4DIR=		$(PROTO_DIR)$(APPLICATION_MAN4DIR)
PROTO_MAN5DIR=		$(PROTO_DIR)$(APPLICATION_MAN5DIR)

