--- haproxy-1.8.9/Makefile.orig	2018-05-25 08:41:20.890957933 +0000
+++ haproxy-1.8.9/Makefile	2018-05-25 08:42:13.760977346 +0000
@@ -133,7 +133,7 @@
 
 #### Toolchain options.
 # GCC is normally used both for compiling and linking.
-CC = gcc
+CC ?= gcc
 LD = $(CC)
 
 #### Debug flags (typically "-g").
