--- lua-5.2.1/src/Makefile.~1~	2012-03-09 16:32:16.000000000 +0000
+++ lua-5.2.1/src/Makefile	2012-10-06 14:22:26.611689987 +0000
@@ -7,11 +7,12 @@
 PLAT= none
 
 CC= gcc
-CFLAGS= -O2 -Wall -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)
+CFLAGS= -Wall -DLUA_COMPAT_ALL $(SYSCFLAGS) $(MYCFLAGS)
 LDFLAGS= $(SYSLDFLAGS) $(MYLDFLAGS)
 LIBS= -lm $(SYSLIBS) $(MYLIBS)
 
-AR= ar rcu
+AR= ar
+ARRFLAGS= rcu
 RANLIB= ranlib
 RM= rm -f
 
@@ -19,9 +20,6 @@
 SYSLDFLAGS=
 SYSLIBS=
 
-MYCFLAGS=
-MYLDFLAGS=
-MYLIBS=
 MYOBJS=
 
 # == END OF USER SETTINGS -- NO NEED TO CHANGE ANYTHING BELOW THIS LINE =======
@@ -38,12 +36,13 @@
 
 LUA_T=	lua
 LUA_O=	lua.o
+LUA_SO=	liblua-$(LUA_VER).so
 
 LUAC_T=	luac
 LUAC_O=	luac.o
 
 ALL_O= $(BASE_O) $(LUA_O) $(LUAC_O)
-ALL_T= $(LUA_A) $(LUA_T) $(LUAC_T)
+ALL_T= $(LUA_A) $(LUA_T) $(LUAC_T) $(LUA_SO)
 ALL_A= $(LUA_A)
 
 # Targets start here.
@@ -55,8 +54,11 @@
 
 a:	$(ALL_A)
 
+$(LUA_SO):	$(CORE_O) $(LIB_O)
+	$(CC) -shared -Wl,-soname=$@ -o $@ $(CFLAGS) $(LDFLAGS) $(MYLDFLAGS) $?
+
 $(LUA_A): $(BASE_O)
-	$(AR) $@ $(BASE_O)
+	$(AR) $(ARRFLAGS) $@ $?
 	$(RANLIB) $@
 
 $(LUA_T): $(LUA_O) $(LUA_A)
