#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 EveryCity Ltd. All rights reserved.
#

COMPONENT_FMRI=		runtime/ruby-26
COMPONENT_MJR_VERSION=	2.6
COMPONENT_MNR_VERSION=	3
COMPONENT_ARCHIVE_HASH=	sha256:577fd3795f22b8d91c1d4e6733637b0394d4082db659fccf224c774a2b1c82fb

include ../../meta-packages/ruby/Makefile.common
