#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 EveryCity Ltd. All rights reserved.
#

COMPONENT_FMRI=		runtime/ruby-25
COMPONENT_MJR_VERSION=	2.5
COMPONENT_MNR_VERSION=	5
COMPONENT_ARCHIVE_HASH=	sha256:28a945fdf340e6ba04fc890b98648342e3cccfd6d223a48f3810572f11b2514c

include ../../meta-packages/ruby/Makefile.common
