#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2019 EveryCity Ltd. All rights reserved.
#

COMPONENT_FMRI=		runtime/ruby-23
COMPONENT_MJR_VERSION=	2.3
COMPONENT_MNR_VERSION=	8
COMPONENT_ARCHIVE_HASH=	sha256:b5016d61440e939045d4e22979e04708ed6c8e1c52e7edb2553cf40b73c59abf

include ../../meta-packages/ruby/Makefile.common
