--- rabbitmq-server-3.6.6/Makefile.orig	2016-12-13 11:38:39.638882745 +0000
+++ rabbitmq-server-3.6.6/Makefile	2016-12-13 11:39:15.693955368 +0000
@@ -351,7 +351,7 @@
 
 install-windows-docs: install-windows-erlapp
 	$(verbose) mkdir -p $(DESTDIR)$(WINDOWS_PREFIX)/etc
-	$(inst_verbose) xmlto -o . xhtml-nochunks \
+	$(inst_verbose) xmlto --skip-validation -o . xhtml-nochunks \
 		$(DEPS_DIR)/rabbit/docs/rabbitmq-service.xml
 	$(verbose) elinks -dump -no-references -no-numbering \
 		rabbitmq-service.html \
