#!/bin/sh

[ ! x$1 = x ] && CFGFILE=$1 || CFGFILE="/ec/etc/haproxy/haproxy.cfg"

CTID=$(ps -o ctid= -p $$)
HAPROXY=$(dirname $0)/haproxy
CMD="$HAPROXY -f $CFGFILE"

restart() {
    $CMD -$1 $(pgrep -f -c $CTID "$CMD") &
    wait $!
}

# graceful restart
trap "restart sf" SIGUSR1
# forceful restart
trap "restart st" SIGHUP

$CMD &
wait $!
