#!/usr/xpg4/bin/sh
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2012 EveryCity Ltd. All rights reserved.
#

. /lib/svc/share/smf_include.sh

# Do not change these defaults below, they will be overwritten
# during the next package upgrade. Instead, set these properties
# via SMF using "svccfg -s haproxy:default" and setprop

config_file="/ec/etc/haproxy/haproxy.cfg"
haproxy_options=""

getprop() {
    PROPVAL=""
    svcprop -q -p $1 ${SMF_FMRI}
    if [ $? -eq 0 ] ; then
        PROPVAL=`svccfg -s ${SMF_FMRI} listprop $1 | \
                /usr/bin/nawk '{ for (i = 3; i <= NF; i++) printf $i" " }' | \
                /usr/bin/nawk '{ sub(/^\"/,""); sub(/\"[ \t]*$/,""); print }' | \
                /usr/bin/sed 's/[ ]*$//g'`
        if [ "${PROPVAL}" = "\"\"" ] ; then
            PROPVAL=""
        fi
        return
    fi
    return
}

varprop() {
  getprop haproxy/$1
  if [ "${PROPVAL}" != "" ] ; then
    export $1="${PROPVAL}"
  fi
}

ISADIR=
getprop haproxy/enable_64bit
if [ "${PROPVAL}" != "" ] ; then
    case ${PROPVAL} in
    true|1)
        # Check if the system architecture supports 64-bit applications
        PLATFORM=`isainfo -b`
        if [ "${PLATFORM}" != "64" ]; then
            echo "This system is not capable of supporting 64-bit applications."
            echo "Set \"enable_64bit\" property value to \"false\" to start the 32-bit server."
            exit $SMF_EXIT_ERR_CONFIG
        fi

        # 64 bit
        ISADIR=amd64/
        ;;
    false|0)
        # 32 bit
        ;;
    *)
        # Invalid value for "bitness"
        echo "\"bitness\" property value is invalid. Starting the server in 32-bit mode"
        ;;
    esac
fi
haproxy_binary="/ec/bin/${ISADIR}haproxy"

varprop config_file
varprop additional_startup_options

case "$1" in
  start)
    echo "Starting haproxy: \c"
    $haproxy_binary -f $config_file $additional_startup_options
    echo "haproxy."
    ;;
  *)
    echo "Usage: $0 {start}"
    exit 1
    ;;
esac

exit $SMF_EXIT_OK

