#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL)". You may
# only use this file in accordance with the terms of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source. A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 EveryCity Ltd. All rights reserved.
#

COMPONENT_MJR_VERSION=	9.4
COMPONENT_MNR_VERSION=	11
COMPONENT_ARCHIVE_HASH=	sha256:e3eb51d045c180b03d2de1f0c3af9356e10be49448e966ca01dfc2c6d1cc9d23

PG_CONTRIB_BINS+=	pgbench
PG_CONTRIB_LIBS+=	uuid-ossp

include ../meta-packages/postgresql/Makefile.common
