--- LuaJIT-2.0.3/Makefile.~1~	2014-03-12 12:10:00.000000000 +0000
+++ LuaJIT-2.0.3/Makefile	2014-12-01 15:38:45.366552244 +0000
@@ -25,11 +25,12 @@
 # the paths in src/luaconf.h, too. Note: PREFIX must be an absolute path!
 #
 export PREFIX= /usr/local
+export BINDIR= bin
 export MULTILIB= lib
 ##############################################################################
 
 DPREFIX= $(DESTDIR)$(PREFIX)
-INSTALL_BIN=   $(DPREFIX)/bin
+INSTALL_BIN=   $(DPREFIX)/$(BINDIR)
 INSTALL_LIB=   $(DPREFIX)/$(MULTILIB)
 INSTALL_SHARE= $(DPREFIX)/share
 INSTALL_INC=   $(DPREFIX)/include/luajit-$(MAJVER).$(MINVER)
